const CROP_CATALOG_SEED = [
  {
    nameEn: 'Rice (Paddy)',
    nameMr: 'भात / तांदूळ',
    scientificName: 'Oryza sativa',
    soilType: 'clay, loamy',
    season: 'Kharif',
    sowingMonth: 'June–July',
    harvestMonth: 'October–November',
    waterRequirement: 'High',
    avgYield: '18–22 quintal/acre',
    priceRange: '₹1800–2200/quintal',
    description:
      'Staple cereal grown in high-rainfall and irrigated tracts of Konkan and Vidarbha; needs standing water for most of its growth.',
    commonDiseases: 'Blast, Bacterial Leaf Blight, Sheath Blight',
    recommendedFertilizer: 'NPK 100:50:50 kg/ha in 3 split nitrogen doses',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Rice_Field.jpg?width=500',
  },
  {
    nameEn: 'Wheat',
    nameMr: 'गहू',
    scientificName: 'Triticum aestivum',
    soilType: 'loamy, clay',
    season: 'Rabi',
    sowingMonth: 'November',
    harvestMonth: 'March',
    waterRequirement: 'Medium',
    avgYield: '14–18 quintal/acre',
    priceRange: '₹2000–2400/quintal',
    description: 'Cool-season cereal sown after monsoon withdrawal; performs best with 5–6 timed irrigations.',
    commonDiseases: 'Rust (yellow/brown), Karnal Bunt, Powdery Mildew',
    recommendedFertilizer: 'NPK 120:60:40 kg/ha, nitrogen split at sowing and irrigations',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/A_field_of_wheat.JPG?width=500',
  },
  {
    nameEn: 'Jowar (Sorghum)',
    nameMr: 'ज्वारी',
    scientificName: 'Sorghum bicolor',
    soilType: 'black, loamy',
    season: 'Kharif, Rabi',
    sowingMonth: 'June or October',
    harvestMonth: 'September or February',
    waterRequirement: 'Low',
    avgYield: '10–14 quintal/acre',
    priceRange: '₹2500–3000/quintal',
    description:
      'Hardy, drought-tolerant cereal widely grown across Marathwada; Rabi jowar is a Maharashtra specialty for roti flour.',
    commonDiseases: 'Grain Smut, Anthracnose, Shoot Fly',
    recommendedFertilizer: 'NPK 80:40:40 kg/ha as basal + top dress',
    imageUrl: '',
  },
  {
    nameEn: 'Bajra (Pearl Millet)',
    nameMr: 'बाजरी',
    scientificName: 'Pennisetum glaucum',
    soilType: 'sandy, loamy',
    season: 'Kharif',
    sowingMonth: 'June–July',
    harvestMonth: 'September',
    waterRequirement: 'Low',
    avgYield: '8–12 quintal/acre',
    priceRange: '₹2000–2400/quintal',
    description: 'Fast-growing millet suited to light sandy soils and low-rainfall belts of western Maharashtra.',
    commonDiseases: 'Downy Mildew, Ergot, Smut',
    recommendedFertilizer: 'NPK 60:30:30 kg/ha',
    imageUrl: '',
  },
  {
    nameEn: 'Maize',
    nameMr: 'मका',
    scientificName: 'Zea mays',
    soilType: 'loamy, sandy',
    season: 'Kharif, Rabi',
    sowingMonth: 'June or November',
    harvestMonth: 'September or March',
    waterRequirement: 'Medium',
    avgYield: '22–28 quintal/acre',
    priceRange: '₹1800–2100/quintal',
    description:
      'Versatile cereal used for grain, fodder and sweet corn; responds strongly to fertilizer and irrigation.',
    commonDiseases: 'Turcicum Leaf Blight, Fall Armyworm, Stalk Rot',
    recommendedFertilizer: 'NPK 120:60:40 kg/ha in split doses',
    imageUrl: '',
  },
  {
    nameEn: 'Cotton',
    nameMr: 'कापूस',
    scientificName: 'Gossypium hirsutum',
    soilType: 'black, loamy',
    season: 'Kharif',
    sowingMonth: 'June',
    harvestMonth: 'November–January',
    waterRequirement: 'Medium',
    avgYield: '6–9 quintal/acre (lint)',
    priceRange: '₹6500–7500/quintal',
    description: "Maharashtra's leading cash crop, grown extensively on Vidarbha and Marathwada's black cotton soils.",
    commonDiseases: 'Pink Bollworm, Wilt, Leaf Curl Virus',
    recommendedFertilizer: 'NPK 100:50:50 kg/ha in splits at sowing, squaring, flowering',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Cotton_plant.jpg?width=500',
  },
  {
    nameEn: 'Sugarcane',
    nameMr: 'ऊस',
    scientificName: 'Saccharum officinarum',
    soilType: 'loamy, clay',
    season: 'Annual',
    sowingMonth: 'October or February',
    harvestMonth: '12–14 months after planting',
    waterRequirement: 'High',
    avgYield: '35–45 tonnes/acre',
    priceRange: '₹2800–3200/tonne (FRP-linked)',
    description: "Long-duration, water-intensive cash crop concentrated in western Maharashtra's sugar belt.",
    commonDiseases: 'Red Rot, Smut, Woolly Aphid',
    recommendedFertilizer: 'NPK 250:115:115 kg/ha in staged doses across the crop cycle',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Sugarcane_farm,_Bhuinj_02.jpg?width=500',
  },
  {
    nameEn: 'Soybean',
    nameMr: 'सोयाबीन',
    scientificName: 'Glycine max',
    soilType: 'black, loamy',
    season: 'Kharif',
    sowingMonth: 'June–July',
    harvestMonth: 'October',
    waterRequirement: 'Medium',
    avgYield: '9–12 quintal/acre',
    priceRange: '₹4200–4800/quintal',
    description: 'Oilseed-cum-pulse crop that has rapidly expanded across Vidarbha and Marathwada in recent decades.',
    commonDiseases: 'Yellow Mosaic Virus, Rust, Pod Blight',
    recommendedFertilizer: 'NPK 30:60:30 kg/ha basal; being a legume, avoid excess nitrogen',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Soybean.USDA.jpg?width=500',
  },
  {
    nameEn: 'Tur (Pigeon Pea)',
    nameMr: 'तूर',
    scientificName: 'Cajanus cajan',
    soilType: 'black, sandy, loamy',
    season: 'Kharif',
    sowingMonth: 'June–July',
    harvestMonth: 'December–January',
    waterRequirement: 'Low',
    avgYield: '6–8 quintal/acre',
    priceRange: '₹6500–7500/quintal',
    description: 'Deep-rooted pulse mostly rainfed; a key protein source and common intercrop with cotton or soybean.',
    commonDiseases: 'Fusarium Wilt, Sterility Mosaic, Pod Borer',
    recommendedFertilizer: 'NPK 25:50:0 kg/ha basal only',
    imageUrl: '',
  },
  {
    nameEn: 'Moong (Green Gram)',
    nameMr: 'मूग',
    scientificName: 'Vigna radiata',
    soilType: 'loamy, sandy',
    season: 'Kharif, Zaid',
    sowingMonth: 'June or March',
    harvestMonth: 'September or May',
    waterRequirement: 'Low',
    avgYield: '3–5 quintal/acre',
    priceRange: '₹7000–8000/quintal',
    description: 'Short-duration summer/monsoon pulse, useful as a quick catch crop between main seasons.',
    commonDiseases: 'Yellow Mosaic Virus, Cercospora Leaf Spot',
    recommendedFertilizer: 'NPK 20:40:0 kg/ha',
    imageUrl: '',
  },
  {
    nameEn: 'Udid (Black Gram)',
    nameMr: 'उडीद',
    scientificName: 'Vigna mungo',
    soilType: 'loamy, black',
    season: 'Kharif',
    sowingMonth: 'June–July',
    harvestMonth: 'September–October',
    waterRequirement: 'Low',
    avgYield: '3–5 quintal/acre',
    priceRange: '₹6800–7800/quintal',
    description: 'Short-duration pulse grown similarly to moong; enriches soil nitrogen for the following crop.',
    commonDiseases: 'Yellow Mosaic Virus, Leaf Crinkle, Powdery Mildew',
    recommendedFertilizer: 'NPK 20:40:0 kg/ha',
    imageUrl: '',
  },
  {
    nameEn: 'Chana (Chickpea)',
    nameMr: 'हरभरा',
    scientificName: 'Cicer arietinum',
    soilType: 'black, loamy',
    season: 'Rabi',
    sowingMonth: 'October–November',
    harvestMonth: 'February–March',
    waterRequirement: 'Low',
    avgYield: '8–10 quintal/acre',
    priceRange: '₹5000–5500/quintal',
    description: 'Major Rabi pulse grown on residual moisture after Kharif harvest across the black-soil belt.',
    commonDiseases: 'Wilt, Ascochyta Blight, Pod Borer',
    recommendedFertilizer: 'NPK 20:40:0 kg/ha basal',
    imageUrl: '',
  },
  {
    nameEn: 'Groundnut',
    nameMr: 'भुईमूग',
    scientificName: 'Arachis hypogaea',
    soilType: 'sandy, loamy',
    season: 'Kharif, Zaid',
    sowingMonth: 'June or January',
    harvestMonth: 'October or April',
    waterRequirement: 'Medium',
    avgYield: '10–14 quintal/acre',
    priceRange: '₹5500–6200/quintal',
    description: 'Oilseed legume needing well-drained sandy loam; gypsum application improves pod filling.',
    commonDiseases: 'Tikka Leaf Spot, Rust, Collar Rot',
    recommendedFertilizer: 'NPK 25:50:75 kg/ha basal',
    imageUrl: '',
  },
  {
    nameEn: 'Sunflower',
    nameMr: 'सूर्यफूल',
    scientificName: 'Helianthus annuus',
    soilType: 'loamy, black',
    season: 'Kharif, Rabi, Zaid',
    sowingMonth: 'June or November',
    harvestMonth: 'September or February',
    waterRequirement: 'Medium',
    avgYield: '6–8 quintal/acre',
    priceRange: '₹5500–6200/quintal',
    description: 'Short-duration oilseed that tolerates moisture stress better than most other oilseeds.',
    commonDiseases: 'Alternaria Blight, Downy Mildew, Head Rot',
    recommendedFertilizer: 'NPK 60:30:30 kg/ha',
    imageUrl: '',
  },
  {
    nameEn: 'Safflower',
    nameMr: 'करडई',
    scientificName: 'Carthamus tinctorius',
    soilType: 'black, loamy',
    season: 'Rabi',
    sowingMonth: 'October',
    harvestMonth: 'February–March',
    waterRequirement: 'Low',
    avgYield: '5–7 quintal/acre',
    priceRange: '₹5500–6500/quintal',
    description: 'Deep-rooted, drought-hardy Rabi oilseed traditionally grown on residual black-soil moisture.',
    commonDiseases: 'Aphid infestation, Wilt, Alternaria Leaf Spot',
    recommendedFertilizer: 'NPK 40:20:0 kg/ha basal',
    imageUrl: '',
  },
  {
    nameEn: 'Onion',
    nameMr: 'कांदा',
    scientificName: 'Allium cepa',
    soilType: 'loamy, sandy',
    season: 'Rabi, Kharif',
    sowingMonth: 'October or June (nursery)',
    harvestMonth: 'February or October',
    waterRequirement: 'Low',
    avgYield: '80–120 quintal/acre',
    priceRange: '₹1000–2500/quintal (highly variable)',
    description: "Maharashtra's flagship vegetable/cash crop (Nashik belt); prices swing sharply with supply.",
    commonDiseases: 'Purple Blotch, Thrips, Basal Rot',
    recommendedFertilizer: 'NPK 100:50:50 kg/ha, nitrogen in 2 splits',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Onions.jpg?width=500',
  },
  {
    nameEn: 'Tomato',
    nameMr: 'टोमॅटो',
    scientificName: 'Solanum lycopersicum',
    soilType: 'loamy, sandy',
    season: 'Rabi, Kharif',
    sowingMonth: 'June or October',
    harvestMonth: 'September or January',
    waterRequirement: 'Medium',
    avgYield: '150–200 quintal/acre',
    priceRange: '₹800–2000/quintal (highly variable)',
    description: 'High-value vegetable best grown on raised beds with drip irrigation to avoid fruit cracking.',
    commonDiseases: 'Early Blight, Blossom-End Rot, Fruit Borer',
    recommendedFertilizer: 'NPK 100:50:50 kg/ha; calcium helps reduce blossom-end rot',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Tomatoes.jpg?width=500',
  },
  {
    nameEn: 'Potato',
    nameMr: 'बटाटा',
    scientificName: 'Solanum tuberosum',
    soilType: 'loamy, sandy',
    season: 'Rabi',
    sowingMonth: 'October–November',
    harvestMonth: 'January–February',
    waterRequirement: 'Medium',
    avgYield: '80–100 quintal/acre',
    priceRange: '₹800–1400/quintal',
    description: 'Cool-season tuber crop needing loose, well-drained soil for good tuber development.',
    commonDiseases: 'Late Blight, Early Blight, Common Scab',
    recommendedFertilizer: 'NPK 120:60:60 kg/ha',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Potatoes.jpg?width=500',
  },
  {
    nameEn: 'Brinjal (Eggplant)',
    nameMr: 'वांगे',
    scientificName: 'Solanum melongena',
    soilType: 'loamy, sandy',
    season: 'Kharif, Rabi',
    sowingMonth: 'June or October',
    harvestMonth: 'September onward (long picking window)',
    waterRequirement: 'Medium',
    avgYield: '120–160 quintal/acre',
    priceRange: '₹1000–1800/quintal',
    description: 'Widely grown vegetable with a long harvest window of repeated pickings.',
    commonDiseases: 'Fruit & Shoot Borer, Bacterial Wilt, Little Leaf',
    recommendedFertilizer: 'NPK 100:50:50 kg/ha',
    imageUrl: '',
  },
  {
    nameEn: 'Cabbage',
    nameMr: 'कोबी',
    scientificName: 'Brassica oleracea var. capitata',
    soilType: 'loamy',
    season: 'Rabi',
    sowingMonth: 'September–October',
    harvestMonth: 'December–January',
    waterRequirement: 'Medium',
    avgYield: '150–200 quintal/acre',
    priceRange: '₹600–1200/quintal',
    description: 'Cool-season leafy vegetable that heads best in mild winter temperatures.',
    commonDiseases: 'Black Rot, Diamondback Moth, Clubroot',
    recommendedFertilizer: 'NPK 100:50:50 kg/ha',
    imageUrl: '',
  },
  {
    nameEn: 'Cauliflower',
    nameMr: 'फ्लॉवर',
    scientificName: 'Brassica oleracea var. botrytis',
    soilType: 'loamy',
    season: 'Rabi',
    sowingMonth: 'September–October',
    harvestMonth: 'December–January',
    waterRequirement: 'Medium',
    avgYield: '100–140 quintal/acre',
    priceRange: '₹800–1500/quintal',
    description: 'Related to cabbage; needs consistent moisture for compact, well-formed curds.',
    commonDiseases: 'Black Rot, Curd Blackening, Aphids',
    recommendedFertilizer: 'NPK 100:60:60 kg/ha',
    imageUrl: '',
  },
  {
    nameEn: 'Okra (Bhendi)',
    nameMr: 'भेंडी',
    scientificName: 'Abelmoschus esculentus',
    soilType: 'loamy, sandy',
    season: 'Kharif, Zaid',
    sowingMonth: 'June or February',
    harvestMonth: 'August onward (long picking window)',
    waterRequirement: 'Medium',
    avgYield: '60–90 quintal/acre',
    priceRange: '₹1200–2000/quintal',
    description: 'Fast-growing summer/monsoon vegetable with frequent picking over an extended season.',
    commonDiseases: 'Yellow Vein Mosaic Virus, Fruit Borer, Powdery Mildew',
    recommendedFertilizer: 'NPK 80:40:40 kg/ha',
    imageUrl: '',
  },
  {
    nameEn: 'Chilli',
    nameMr: 'मिरची',
    scientificName: 'Capsicum annuum',
    soilType: 'loamy, black',
    season: 'Kharif, Rabi',
    sowingMonth: 'June or November',
    harvestMonth: 'October onward (multiple pickings)',
    waterRequirement: 'Medium',
    avgYield: '25–35 quintal/acre (dry)',
    priceRange: '₹8000–14000/quintal (dry, variable)',
    description: 'High-value spice crop grown for both fresh green and dried red chilli markets.',
    commonDiseases: 'Thrips/Leaf Curl Complex, Anthracnose, Wilt',
    recommendedFertilizer: 'NPK 100:50:50 kg/ha',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Kashmiri_Red_Chilli.JPG?width=500',
  },
  {
    nameEn: 'Turmeric',
    nameMr: 'हळद',
    scientificName: 'Curcuma longa',
    soilType: 'loamy, clay',
    season: 'Kharif',
    sowingMonth: 'May–June',
    harvestMonth: 'January–March (8–9 month duration)',
    waterRequirement: 'High',
    avgYield: '80–100 quintal/acre (fresh rhizome)',
    priceRange: '₹6000–8000/quintal',
    description: 'Long-duration rhizome spice crop; Sangli/Hingoli belts are known turmeric markets.',
    commonDiseases: 'Rhizome Rot, Leaf Blotch, Leaf Spot',
    recommendedFertilizer: 'NPK 60:50:50 kg/ha',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Turmeric.JPG?width=500',
  },
  {
    nameEn: 'Ginger',
    nameMr: 'आले',
    scientificName: 'Zingiber officinale',
    soilType: 'loamy',
    season: 'Kharif',
    sowingMonth: 'May–June',
    harvestMonth: 'December–January',
    waterRequirement: 'High',
    avgYield: '70–90 quintal/acre',
    priceRange: '₹5000–9000/quintal (variable)',
    description: 'Rhizome spice crop needing well-drained, humus-rich soil and partial shade.',
    commonDiseases: 'Rhizome Rot, Bacterial Wilt, Leaf Spot',
    recommendedFertilizer: 'NPK 75:50:50 kg/ha',
    imageUrl: '',
  },
  {
    nameEn: 'Garlic',
    nameMr: 'लसूण',
    scientificName: 'Allium sativum',
    soilType: 'loamy, sandy',
    season: 'Rabi',
    sowingMonth: 'October–November',
    harvestMonth: 'February–March',
    waterRequirement: 'Low',
    avgYield: '40–60 quintal/acre',
    priceRange: '₹4000–10000/quintal (highly variable)',
    description: 'Bulb crop that prefers cool weather during vegetative growth and dry weather at maturity.',
    commonDiseases: 'Purple Blotch, Thrips, White Rot',
    recommendedFertilizer: 'NPK 60:40:40 kg/ha',
    imageUrl: '',
  },
  {
    nameEn: 'Grapes',
    nameMr: 'द्राक्ष',
    scientificName: 'Vitis vinifera',
    soilType: 'loamy, sandy',
    season: 'Perennial (pruned twice yearly)',
    sowingMonth: 'Planted June–July; pruned Oct and April',
    harvestMonth: 'January–March (main season)',
    waterRequirement: 'Medium',
    avgYield: '80–120 quintal/acre',
    priceRange: '₹3000–6000/quintal (table grapes)',
    description: "Nashik region's signature export crop; trellised vines need precise double-pruning cycles.",
    commonDiseases: 'Downy Mildew, Powdery Mildew, Anthracnose',
    recommendedFertilizer: 'NPK 400:200:200 g/vine/year staged across phenophases',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Grapes.jpg?width=500',
  },
  {
    nameEn: 'Banana',
    nameMr: 'केळी',
    scientificName: 'Musa spp.',
    soilType: 'loamy, clay',
    season: 'Perennial',
    sowingMonth: 'June or February (tissue-culture plantlets)',
    harvestMonth: '11–13 months after planting',
    waterRequirement: 'High',
    avgYield: '250–350 quintal/acre',
    priceRange: '₹800–1500/quintal',
    description: 'Jalgaon is a major banana belt; the crop needs consistent irrigation and wind protection.',
    commonDiseases: 'Panama Wilt, Sigatoka Leaf Spot, Bunchy Top Virus',
    recommendedFertilizer: 'NPK 200:60:300 g/plant/year in split doses',
    imageUrl:
      'https://commons.wikimedia.org/wiki/Special:FilePath/Banana_Plantation_-_Bhaktanagar_-_Nadia_2017-08-15_2363.JPG?width=500',
  },
  {
    nameEn: 'Mango',
    nameMr: 'आंबा',
    scientificName: 'Mangifera indica',
    soilType: 'loamy, red',
    season: 'Perennial',
    sowingMonth: 'June–July (grafted saplings)',
    harvestMonth: 'March–June',
    waterRequirement: 'Medium',
    avgYield: '40–60 quintal/acre (mature orchard)',
    priceRange: '₹3000–8000/quintal (variety-dependent, e.g. Alphonso)',
    description: "Konkan's Alphonso (Hapus) is Maharashtra's most iconic fruit crop, grown on lateritic hill soils.",
    commonDiseases: 'Powdery Mildew, Anthracnose, Fruit Fly',
    recommendedFertilizer: 'NPK 500:250:500 g/tree/year for a mature tree',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Mango_fruits.JPG?width=500',
  },
  {
    nameEn: 'Pomegranate',
    nameMr: 'डाळिंब',
    scientificName: 'Punica granatum',
    soilType: 'loamy, black',
    season: 'Perennial (bahar-based flowering)',
    sowingMonth: 'June–July',
    harvestMonth: '5–6 months after flowering (bahar)',
    waterRequirement: 'Low',
    avgYield: '80–100 quintal/acre',
    priceRange: '₹4000–9000/quintal',
    description:
      "Drought-tolerant fruit crop centered in Solapur/Ahmednagar, managed through timed 'bahar' flowering cycles.",
    commonDiseases: 'Bacterial Blight, Wilt, Fruit Borer',
    recommendedFertilizer: 'NPK 625:250:250 g/plant/year',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Pomegranate.JPG?width=500',
  },
  {
    nameEn: 'Orange (Nagpur Mandarin)',
    nameMr: 'संत्रा',
    scientificName: 'Citrus reticulata',
    soilType: 'loamy, black',
    season: 'Perennial (two flowering flushes)',
    sowingMonth: 'June–July or February',
    harvestMonth: 'November–January (Ambia) or June–July (Mrig)',
    waterRequirement: 'Medium',
    avgYield: '60–90 quintal/acre',
    priceRange: '₹1500–3500/quintal',
    description: "Vidarbha's Nagpur mandarin is one of India's best-known citrus varieties.",
    commonDiseases: 'Citrus Canker, Gummosis, Leaf Miner',
    recommendedFertilizer: 'NPK 600:200:200 g/tree/year for bearing trees',
    imageUrl: '',
  },
  {
    nameEn: 'Sapota (Chikoo)',
    nameMr: 'चिकू',
    scientificName: 'Manilkara zapota',
    soilType: 'loamy, sandy',
    season: 'Perennial',
    sowingMonth: 'June–July (grafted saplings)',
    harvestMonth: 'Year-round with peak in Nov–Feb',
    waterRequirement: 'Medium',
    avgYield: '100–150 quintal/acre (mature orchard)',
    priceRange: '₹1500–2500/quintal',
    description: 'Hardy evergreen fruit tree well suited to coastal Konkan; bears almost continuously once mature.',
    commonDiseases: 'Leaf Spot, Bark Borer, Fruit Fly',
    recommendedFertilizer: 'NPK 500:250:250 g/tree/year',
    imageUrl: '',
  },
  {
    nameEn: 'Guava',
    nameMr: 'पेरू',
    scientificName: 'Psidium guajava',
    soilType: 'loamy, sandy',
    season: 'Perennial (two crops: Ambe & Mrig bahar)',
    sowingMonth: 'June–July or February',
    harvestMonth: 'October–December or June–July',
    waterRequirement: 'Low',
    avgYield: '100–150 quintal/acre',
    priceRange: '₹1000–2000/quintal',
    description: 'Resilient fruit tree that tolerates poor soils better than most orchard crops.',
    commonDiseases: 'Wilt, Anthracnose, Fruit Fly',
    recommendedFertilizer: 'NPK 300:150:300 g/tree/year',
    imageUrl: '',
  },
  {
    nameEn: 'Papaya',
    nameMr: 'पपई',
    scientificName: 'Carica papaya',
    soilType: 'loamy, sandy',
    season: 'Perennial (planted year-round in irrigated areas)',
    sowingMonth: 'June–July or February–March',
    harvestMonth: '9–11 months after planting',
    waterRequirement: 'Medium',
    avgYield: '400–600 quintal/acre',
    priceRange: '₹500–1200/quintal',
    description: 'Fast-yielding fruit crop that bears within a year; sensitive to waterlogging.',
    commonDiseases: 'Papaya Ring Spot Virus, Root Rot, Powdery Mildew',
    recommendedFertilizer: 'NPK 250:250:500 g/plant/year',
    imageUrl: '',
  },
  {
    nameEn: 'Watermelon',
    nameMr: 'कलिंगड',
    scientificName: 'Citrullus lanatus',
    soilType: 'sandy, loamy',
    season: 'Zaid',
    sowingMonth: 'January–February',
    harvestMonth: 'April–May',
    waterRequirement: 'Medium',
    avgYield: '150–200 quintal/acre',
    priceRange: '₹600–1200/quintal',
    description: 'Summer melon grown on riverbed sandy tracts, timed to ripen before peak summer heat.',
    commonDiseases: 'Fusarium Wilt, Downy Mildew, Fruit Fly',
    recommendedFertilizer: 'NPK 60:40:40 kg/ha',
    imageUrl: '',
  },
  {
    nameEn: 'Sesame (Til)',
    nameMr: 'तीळ',
    scientificName: 'Sesamum indicum',
    soilType: 'sandy, loamy',
    season: 'Kharif, Zaid',
    sowingMonth: 'June–July or February',
    harvestMonth: 'September or May',
    waterRequirement: 'Low',
    avgYield: '3–4 quintal/acre',
    priceRange: '₹9000–12000/quintal',
    description: 'Short-duration, drought-hardy oilseed traditionally intercropped with pulses.',
    commonDiseases: 'Phyllody, Leaf Spot, Stem/Root Rot',
    recommendedFertilizer: 'NPK 25:25:0 kg/ha',
    imageUrl: '',
  },
  {
    nameEn: 'Castor',
    nameMr: 'एरंड',
    scientificName: 'Ricinus communis',
    soilType: 'sandy, loamy, black',
    season: 'Kharif',
    sowingMonth: 'June–July',
    harvestMonth: 'December onward (multiple pickings)',
    waterRequirement: 'Low',
    avgYield: '10–14 quintal/acre',
    priceRange: '₹6000–7000/quintal',
    description: 'Hardy industrial oilseed tolerant of poor soils and moisture stress.',
    commonDiseases: 'Wilt, Grey Rot, Semi-looper',
    recommendedFertilizer: 'NPK 60:40:0 kg/ha',
    imageUrl: '',
  },
  {
    nameEn: 'Mustard',
    nameMr: 'मोहरी / राई',
    scientificName: 'Brassica juncea',
    soilType: 'loamy, sandy',
    season: 'Rabi',
    sowingMonth: 'October',
    harvestMonth: 'February',
    waterRequirement: 'Low',
    avgYield: '5–7 quintal/acre',
    priceRange: '₹5000–5800/quintal',
    description: 'Cool-season oilseed often grown as a border/mixed crop alongside chickpea or wheat.',
    commonDiseases: 'Alternaria Blight, Aphids, White Rust',
    recommendedFertilizer: 'NPK 60:40:20 kg/ha',
    imageUrl: '',
  },
  {
    nameEn: 'Lentil (Masoor)',
    nameMr: 'मसूर',
    scientificName: 'Lens culinaris',
    soilType: 'loamy, clay',
    season: 'Rabi',
    sowingMonth: 'October–November',
    harvestMonth: 'February–March',
    waterRequirement: 'Low',
    avgYield: '6–8 quintal/acre',
    priceRange: '₹6000–6800/quintal',
    description: 'Cool-season pulse grown mainly on conserved soil moisture after the monsoon.',
    commonDiseases: 'Rust, Wilt, Aphids',
    recommendedFertilizer: 'NPK 20:40:0 kg/ha basal',
    imageUrl: '',
  },
];

module.exports = { CROP_CATALOG_SEED };
