const CROP_CATALOG_SEED = [
  {
    "nameEn": "Rice (Paddy)",
    "nameHi": "धान (चावल)",
    "nameMr": "भात / तांदूळ",
    "scientificName": "Oryza sativa",
    "soilType": "clay, loamy",
    "season": "Kharif",
    "sowingMonth": "June–July",
    "harvestMonth": "October–November",
    "waterRequirement": "High",
    "avgYield": "18–22 quintal/acre",
    "avgYieldHi": "18–22 क्विंटल/एकर",
    "avgYieldMr": "18–22 क्विंटल/एकर",
    "priceRange": "₹1800–2200/quintal",
    "priceRangeHi": "₹1800–2200/क्विंटल",
    "priceRangeMr": "₹1800–2200/क्विंटल",
    "description": "Staple cereal grown in high-rainfall and irrigated tracts of Konkan and Vidarbha; needs standing water for most of its growth.",
    "descriptionHi": "कोंकण और विदर्भ के अधिक वर्षा वाले और सिंचित क्षेत्रों में उगाया जाने वाला मुख्य अनाज; अधिकांश विकास के लिए जलभराव की आवश्यकता होती है।",
    "descriptionMr": "कोकण आणि विदर्भातील जास्त पाऊस व सिंचित भागात पिकवले जाणारे मुख्य धान्य; बहुतांश वाढीसाठी साचलेल्या पाण्याची गरज असते.",
    "commonDiseases": "Blast, Bacterial Leaf Blight, Sheath Blight",
    "recommendedFertilizer": "NPK 100:50:50 kg/ha in 3 split nitrogen doses",
    "imageUrl": "/crops/rice.jpg"
  },
  {
    "nameEn": "Wheat",
    "nameHi": "गेहूँ",
    "nameMr": "गहू",
    "scientificName": "Triticum aestivum",
    "soilType": "loamy, clay",
    "season": "Rabi",
    "sowingMonth": "November",
    "harvestMonth": "March",
    "waterRequirement": "Medium",
    "avgYield": "14–18 quintal/acre",
    "avgYieldHi": "14–18 क्विंटल/एकर",
    "avgYieldMr": "14–18 क्विंटल/एकर",
    "priceRange": "₹2000–2400/quintal",
    "priceRangeHi": "₹2000–2400/क्विंटल",
    "priceRangeMr": "₹2000–2400/क्विंटल",
    "description": "Cool-season cereal sown after monsoon withdrawal; performs best with 5–6 timed irrigations.",
    "descriptionHi": "मानसून के बाद बोई जाने वाली ठंडे मौसम की अनाज फसल; 5–6 समयबद्ध सिंचाई के साथ सर्वोत्तम उपज देती है।",
    "descriptionMr": "पावसाळ्यानंतर पेरणी होणारे थंड हंगामी धान्य; 5–6 वेळा नियोजित पाणी दिल्यास सर्वोत्तम उत्पादन मिळते.",
    "commonDiseases": "Rust (yellow/brown), Karnal Bunt, Powdery Mildew",
    "recommendedFertilizer": "NPK 120:60:40 kg/ha, nitrogen split at sowing and irrigations",
    "imageUrl": "/crops/wheat.jpg"
  },
  {
    "nameEn": "Jowar (Sorghum)",
    "nameHi": "ज्वार",
    "nameMr": "ज्वारी",
    "scientificName": "Sorghum bicolor",
    "soilType": "black, loamy",
    "season": "Kharif, Rabi",
    "sowingMonth": "June or October",
    "harvestMonth": "September or February",
    "waterRequirement": "Low",
    "avgYield": "10–14 quintal/acre",
    "avgYieldHi": "10–14 क्विंटल/एकर",
    "avgYieldMr": "10–14 क्विंटल/एकर",
    "priceRange": "₹2500–3000/quintal",
    "priceRangeHi": "₹2500–3000/क्विंटल",
    "priceRangeMr": "₹2500–3000/क्विंटल",
    "description": "Hardy, drought-tolerant cereal widely grown across Marathwada; Rabi jowar is a Maharashtra specialty for roti flour.",
    "descriptionHi": "कठोर, सूखा-सहनशील अनाज, मराठवाड़ा में व्यापक रूप से उगाया जाता है; रबी ज्वार रोटी के आटे के लिए महाराष्ट्र की विशेषता है।",
    "descriptionMr": "कठोर, दुष्काळ-सहनशील धान्य, मराठवाड्यात मोठ्या प्रमाणात पिकवले जाते; रोटीच्या पिठासाठी रब्बी ज्वारी हे महाराष्ट्राचे खास पीक आहे.",
    "commonDiseases": "Grain Smut, Anthracnose, Shoot Fly",
    "recommendedFertilizer": "NPK 80:40:40 kg/ha as basal + top dress",
    "imageUrl": "/crops/jowar.jpg"
  },
  {
    "nameEn": "Bajra (Pearl Millet)",
    "nameHi": "बाजरा",
    "nameMr": "बाजरी",
    "scientificName": "Pennisetum glaucum",
    "soilType": "sandy, loamy",
    "season": "Kharif",
    "sowingMonth": "June–July",
    "harvestMonth": "September",
    "waterRequirement": "Low",
    "avgYield": "8–12 quintal/acre",
    "avgYieldHi": "8–12 क्विंटल/एकर",
    "avgYieldMr": "8–12 क्विंटल/एकर",
    "priceRange": "₹2000–2400/quintal",
    "priceRangeHi": "₹2000–2400/क्विंटल",
    "priceRangeMr": "₹2000–2400/क्विंटल",
    "description": "Fast-growing millet suited to light sandy soils and low-rainfall belts of western Maharashtra.",
    "descriptionHi": "हल्की रेतीली मिट्टी और कम वर्षा वाले पश्चिमी महाराष्ट्र के क्षेत्रों के लिए उपयुक्त तेजी से बढ़ने वाला मोटा अनाज।",
    "descriptionMr": "हलक्या वाळू मिश्रित जमिनीवर आणि पश्चिम महाराष्ट्राच्या कमी पावसाच्या भागासाठी योग्य, लवकर वाढणारे ज्वारीचे (बाजरीचे) पीक.",
    "commonDiseases": "Downy Mildew, Ergot, Smut",
    "recommendedFertilizer": "NPK 60:30:30 kg/ha",
    "imageUrl": "/crops/bajra.jpg"
  },
  {
    "nameEn": "Maize",
    "nameHi": "मक्का",
    "nameMr": "मका",
    "scientificName": "Zea mays",
    "soilType": "loamy, sandy",
    "season": "Kharif, Rabi",
    "sowingMonth": "June or November",
    "harvestMonth": "September or March",
    "waterRequirement": "Medium",
    "avgYield": "22–28 quintal/acre",
    "avgYieldHi": "22–28 क्विंटल/एकर",
    "avgYieldMr": "22–28 क्विंटल/एकर",
    "priceRange": "₹1800–2100/quintal",
    "priceRangeHi": "₹1800–2100/क्विंटल",
    "priceRangeMr": "₹1800–2100/क्विंटल",
    "description": "Versatile cereal used for grain, fodder and sweet corn; responds strongly to fertilizer and irrigation.",
    "descriptionHi": "अनाज, चारा और स्वीट कॉर्न हेतु उपयोगी बहुउपयोगी अनाज; उर्वरक और सिंचाई पर मजबूत प्रतिक्रिया देता है।",
    "descriptionMr": "धान्य, चारा व स्वीट कॉर्नसाठी वापरले जाणारे बहुउपयोगी धान्य; खत व पाण्याला चांगला प्रतिसाद देते.",
    "commonDiseases": "Turcicum Leaf Blight, Fall Armyworm, Stalk Rot",
    "recommendedFertilizer": "NPK 120:60:40 kg/ha in split doses",
    "imageUrl": "/crops/maize.jpg"
  },
  {
    "nameEn": "Cotton",
    "nameHi": "कपास",
    "nameMr": "कापूस",
    "scientificName": "Gossypium hirsutum",
    "soilType": "black, loamy",
    "season": "Kharif",
    "sowingMonth": "June",
    "harvestMonth": "November–January",
    "waterRequirement": "Medium",
    "avgYield": "6–9 quintal/acre (lint)",
    "avgYieldHi": "6–9 क्विंटल/एकर (लिंट)",
    "avgYieldMr": "6–9 क्विंटल/एकर (लिंट)",
    "priceRange": "₹6500–7500/quintal",
    "priceRangeHi": "₹6500–7500/क्विंटल",
    "priceRangeMr": "₹6500–7500/क्विंटल",
    "description": "Maharashtra's leading cash crop, grown extensively on Vidarbha and Marathwada's black cotton soils.",
    "descriptionHi": "विदर्भ और मराठवाड़ा की काली कपास मिट्टी पर व्यापक रूप से उगाई जाने वाली महाराष्ट्र की प्रमुख नकदी फसल।",
    "descriptionMr": "विदर्भ व मराठवाड्याच्या काळ्या कापसाच्या जमिनीवर मोठ्या प्रमाणात पिकवले जाणारे महाराष्ट्राचे आघाडीचे रोख पीक.",
    "commonDiseases": "Pink Bollworm, Wilt, Leaf Curl Virus",
    "recommendedFertilizer": "NPK 100:50:50 kg/ha in splits at sowing, squaring, flowering",
    "imageUrl": "/crops/cotton.jpg"
  },
  {
    "nameEn": "Sugarcane",
    "nameHi": "गन्ना",
    "nameMr": "ऊस",
    "scientificName": "Saccharum officinarum",
    "soilType": "loamy, clay",
    "season": "Annual",
    "sowingMonth": "October or February",
    "harvestMonth": "12–14 months after planting",
    "waterRequirement": "High",
    "avgYield": "35–45 tonnes/acre",
    "avgYieldHi": "35–45 टन/एकर",
    "avgYieldMr": "35–45 टन/एकर",
    "priceRange": "₹2800–3200/tonne (FRP-linked)",
    "priceRangeHi": "₹2800–3200/टन (FRP-लिंक्ड)",
    "priceRangeMr": "₹2800–3200/टन (FRP-आधारित)",
    "description": "Long-duration, water-intensive cash crop concentrated in western Maharashtra's sugar belt.",
    "descriptionHi": "पश्चिम महाराष्ट्र की चीनी पेटी में केंद्रित, लंबी अवधि की, जल-सघन नकदी फसल।",
    "descriptionMr": "पश्चिम महाराष्ट्राच्या साखर पट्ट्यात केंद्रित, दीर्घ कालावधीचे, जास्त पाणी लागणारे रोख पीक.",
    "commonDiseases": "Red Rot, Smut, Woolly Aphid",
    "recommendedFertilizer": "NPK 250:115:115 kg/ha in staged doses across the crop cycle",
    "imageUrl": "/crops/sugarcane.jpg"
  },
  {
    "nameEn": "Soybean",
    "nameHi": "सोयाबीन",
    "nameMr": "सोयाबीन",
    "scientificName": "Glycine max",
    "soilType": "black, loamy",
    "season": "Kharif",
    "sowingMonth": "June–July",
    "harvestMonth": "October",
    "waterRequirement": "Medium",
    "avgYield": "9–12 quintal/acre",
    "avgYieldHi": "9–12 क्विंटल/एकर",
    "avgYieldMr": "9–12 क्विंटल/एकर",
    "priceRange": "₹4200–4800/quintal",
    "priceRangeHi": "₹4200–4800/क्विंटल",
    "priceRangeMr": "₹4200–4800/क्विंटल",
    "description": "Oilseed-cum-pulse crop that has rapidly expanded across Vidarbha and Marathwada in recent decades.",
    "descriptionHi": "तेलहन-सह-दलहन फसल जो हाल के दशकों में विदर्भ और मराठवाड़ा में तेजी से फैली है।",
    "descriptionMr": "तेलबिया-सह-डाळ या पीक अलीकडील दशकांत विदर्भ व मराठवाड्यात वेगाने पसरले आहे.",
    "commonDiseases": "Yellow Mosaic Virus, Rust, Pod Blight",
    "recommendedFertilizer": "NPK 30:60:30 kg/ha basal; being a legume, avoid excess nitrogen",
    "imageUrl": "/crops/soybean.jpg"
  },
  {
    "nameEn": "Tur (Pigeon Pea)",
    "nameHi": "अरहर (तूर)",
    "nameMr": "तूर",
    "scientificName": "Cajanus cajan",
    "soilType": "black, sandy, loamy",
    "season": "Kharif",
    "sowingMonth": "June–July",
    "harvestMonth": "December–January",
    "waterRequirement": "Low",
    "avgYield": "6–8 quintal/acre",
    "avgYieldHi": "6–8 क्विंटल/एकर",
    "avgYieldMr": "6–8 क्विंटल/एकर",
    "priceRange": "₹6500–7500/quintal",
    "priceRangeHi": "₹6500–7500/क्विंटल",
    "priceRangeMr": "₹6500–7500/क्विंटल",
    "description": "Deep-rooted pulse mostly rainfed; a key protein source and common intercrop with cotton or soybean.",
    "descriptionHi": "अधिकतर असिंचित उगाई जाने वाली गहरी जड़ वाली दलहन; कपास या सोयाबीन के साथ प्रमुख प्रोटीन स्रोत और सामान्य अंतरफसल।",
    "descriptionMr": "बहुतांश ओली (असिंचित) घेतली जाणारी खोल मुळांची डाळ; कापूस किंवा सोयाबीनसोबत घेतले जाणारे प्रथिनांचे प्रमुख स्रोत.",
    "commonDiseases": "Fusarium Wilt, Sterility Mosaic, Pod Borer",
    "recommendedFertilizer": "NPK 25:50:0 kg/ha basal only",
    "imageUrl": "/crops/tur.jpg"
  },
  {
    "nameEn": "Moong (Green Gram)",
    "nameHi": "मूंग",
    "nameMr": "मूग",
    "scientificName": "Vigna radiata",
    "soilType": "loamy, sandy",
    "season": "Kharif, Zaid",
    "sowingMonth": "June or March",
    "harvestMonth": "September or May",
    "waterRequirement": "Low",
    "avgYield": "3–5 quintal/acre",
    "avgYieldHi": "3–5 क्विंटल/एकर",
    "avgYieldMr": "3–5 क्विंटल/एकर",
    "priceRange": "₹7000–8000/quintal",
    "priceRangeHi": "₹7000–8000/क्विंटल",
    "priceRangeMr": "₹7000–8000/क्विंटल",
    "description": "Short-duration summer/monsoon pulse, useful as a quick catch crop between main seasons.",
    "descriptionHi": "छोटी अवधि की ग्रीष्म/मानसून दलहन, मुख्य मौसमों के बीच त्वरित कवर फसल के रूप में उपयोगी।",
    "descriptionMr": "अल्प कालावधीची उन्हाळी/पावसाळी डाळ; मुख्य हंगामांमधील त्वरित कव्हर पिक म्हणून उपयुक्त.",
    "commonDiseases": "Yellow Mosaic Virus, Cercospora Leaf Spot",
    "recommendedFertilizer": "NPK 20:40:0 kg/ha",
    "imageUrl": "/crops/moong.jpg"
  },
  {
    "nameEn": "Udid (Black Gram)",
    "nameHi": "उड़द",
    "nameMr": "उडीद",
    "scientificName": "Vigna mungo",
    "soilType": "loamy, black",
    "season": "Kharif",
    "sowingMonth": "June–July",
    "harvestMonth": "September–October",
    "waterRequirement": "Low",
    "avgYield": "3–5 quintal/acre",
    "avgYieldHi": "3–5 क्विंटल/एकर",
    "avgYieldMr": "3–5 क्विंटल/एकर",
    "priceRange": "₹6800–7800/quintal",
    "priceRangeHi": "₹6800–7800/क्विंटल",
    "priceRangeMr": "₹6800–7800/क्विंटल",
    "description": "Short-duration pulse grown similarly to moong; enriches soil nitrogen for the following crop.",
    "descriptionHi": "मूंग के समान उगाई जाने वाली छोटी अवधि की दलहन; अगली फसल के लिए मिट्टी में नाइट्रोजन बढ़ाती है।",
    "descriptionMr": "मूगासारखी अल्प कालावधीची डाळ; पुढील पिकासाठी जमिनीतील नायट्रोजन वाढवते.",
    "commonDiseases": "Yellow Mosaic Virus, Leaf Crinkle, Powdery Mildew",
    "recommendedFertilizer": "NPK 20:40:0 kg/ha",
    "imageUrl": "/crops/udid.jpg"
  },
  {
    "nameEn": "Chana (Chickpea)",
    "nameHi": "चना",
    "nameMr": "हरभरा",
    "scientificName": "Cicer arietinum",
    "soilType": "black, loamy",
    "season": "Rabi",
    "sowingMonth": "October–November",
    "harvestMonth": "February–March",
    "waterRequirement": "Low",
    "avgYield": "8–10 quintal/acre",
    "avgYieldHi": "8–10 क्विंटल/एकर",
    "avgYieldMr": "8–10 क्विंटल/एकर",
    "priceRange": "₹5000–5500/quintal",
    "priceRangeHi": "₹5000–5500/क्विंटल",
    "priceRangeMr": "₹5000–5500/क्विंटल",
    "description": "Major Rabi pulse grown on residual moisture after Kharif harvest across the black-soil belt.",
    "descriptionHi": "खरीफ कटाई के बाद काली मिट्टी की पेटी में अवशिष्ट नमी पर उगाई जाने वाली प्रमुख रबी दलहन।",
    "descriptionMr": "खरीप काढणीनंतर काळ्या जमिनीच्या पट्ट्यात अवशिष्ट ओलाव्यावर घेतले जाणारे प्रमुख रब्बी डाळीचे पीक.",
    "commonDiseases": "Wilt, Ascochyta Blight, Pod Borer",
    "recommendedFertilizer": "NPK 20:40:0 kg/ha basal",
    "imageUrl": "/crops/chana.jpg"
  },
  {
    "nameEn": "Groundnut",
    "nameHi": "मूंगफली",
    "nameMr": "भुईमूग",
    "scientificName": "Arachis hypogaea",
    "soilType": "sandy, loamy",
    "season": "Kharif, Zaid",
    "sowingMonth": "June or January",
    "harvestMonth": "October or April",
    "waterRequirement": "Medium",
    "avgYield": "10–14 quintal/acre",
    "avgYieldHi": "10–14 क्विंटल/एकर",
    "avgYieldMr": "10–14 क्विंटल/एकर",
    "priceRange": "₹5500–6200/quintal",
    "priceRangeHi": "₹5500–6200/क्विंटल",
    "priceRangeMr": "₹5500–6200/क्विंटल",
    "description": "Oilseed legume needing well-drained sandy loam; gypsum application improves pod filling.",
    "descriptionHi": "अच्छी जल-निकासी वाली रेतीली दोमट मिट्टी की आवश्यकता वाली तिलहन-दलहन; जिप्सम फली भरने में सुधार करता है।",
    "descriptionMr": "चांगल्या निचरा असलेल्या वाळूमिश्रित जमिनीची गरज असणारे तेलबिया-डाळ पीक; जिप्सम फोड भरणे सुधारते.",
    "commonDiseases": "Tikka Leaf Spot, Rust, Collar Rot",
    "recommendedFertilizer": "NPK 25:50:75 kg/ha basal",
    "imageUrl": "/crops/groundnut.jpg"
  },
  {
    "nameEn": "Sunflower",
    "nameHi": "सूर्यमुखी",
    "nameMr": "सूर्यफूल",
    "scientificName": "Helianthus annuus",
    "soilType": "loamy, black",
    "season": "Kharif, Rabi, Zaid",
    "sowingMonth": "June or November",
    "harvestMonth": "September or February",
    "waterRequirement": "Medium",
    "avgYield": "6–8 quintal/acre",
    "avgYieldHi": "6–8 क्विंटल/एकर",
    "avgYieldMr": "6–8 क्विंटल/एकर",
    "priceRange": "₹5500–6200/quintal",
    "priceRangeHi": "₹5500–6200/क्विंटल",
    "priceRangeMr": "₹5500–6200/क्विंटल",
    "description": "Short-duration oilseed that tolerates moisture stress better than most other oilseeds.",
    "descriptionHi": "अधिकांश अन्य तिलहनों की तुलना में नमी तनाव को बेहतर सहन करने वाली छोटी अवधि की तिलहन।",
    "descriptionMr": "बहुतेक इतर तेलबियांच्या तुलनेत पाण्याचा ताण चांगला सहन करणारे अल्प कालावधीचे तेलबिया पीक.",
    "commonDiseases": "Alternaria Blight, Downy Mildew, Head Rot",
    "recommendedFertilizer": "NPK 60:30:30 kg/ha",
    "imageUrl": "/crops/sunflower.jpg"
  },
  {
    "nameEn": "Safflower",
    "nameHi": "कुसुम",
    "nameMr": "करडई",
    "scientificName": "Carthamus tinctorius",
    "soilType": "black, loamy",
    "season": "Rabi",
    "sowingMonth": "October",
    "harvestMonth": "February–March",
    "waterRequirement": "Low",
    "avgYield": "5–7 quintal/acre",
    "avgYieldHi": "5–7 क्विंटल/एकर",
    "avgYieldMr": "5–7 क्विंटल/एकर",
    "priceRange": "₹5500–6500/quintal",
    "priceRangeHi": "₹5500–6500/क्विंटल",
    "priceRangeMr": "₹5500–6500/क्विंटल",
    "description": "Deep-rooted, drought-hardy Rabi oilseed traditionally grown on residual black-soil moisture.",
    "descriptionHi": "पारंपरिक रूप से अवशिष्ट काली मिट्टी की नमी पर उगाई जाने वाली गहरी जड़ वाली, सूखा-कठोर रबी तिलहन।",
    "descriptionMr": "पारंपरिकपणे काळ्या जमिनीच्या अवशिष्ट ओलाव्यावर घेतले जाणारे खोल मुळांचे, दुष्काळ-कठोर रब्बी तेलबिया पीक.",
    "commonDiseases": "Aphid infestation, Wilt, Alternaria Leaf Spot",
    "recommendedFertilizer": "NPK 40:20:0 kg/ha basal",
    "imageUrl": "/crops/safflower.jpg"
  },
  {
    "nameEn": "Onion",
    "nameHi": "प्याज",
    "nameMr": "कांदा",
    "scientificName": "Allium cepa",
    "soilType": "loamy, sandy",
    "season": "Rabi, Kharif",
    "sowingMonth": "October or June (nursery)",
    "harvestMonth": "February or October",
    "waterRequirement": "Low",
    "avgYield": "80–120 quintal/acre",
    "avgYieldHi": "80–120 क्विंटल/एकर",
    "avgYieldMr": "80–120 क्विंटल/एकर",
    "priceRange": "₹1000–2500/quintal (highly variable)",
    "priceRangeHi": "₹1000–2500/क्विंटल (अत्यंत परिवर्तनशील)",
    "priceRangeMr": "₹1000–2500/क्विंटल (अत्यंत परिवर्तनशील)",
    "description": "Maharashtra's flagship vegetable/cash crop (Nashik belt); prices swing sharply with supply.",
    "descriptionHi": "नाशिक क्षेत्र में महाराष्ट्र की प्रमुख सब्जी/नकदी फसल; आपूर्ति के साथ कीमतें तेजी से बदलती हैं।",
    "descriptionMr": "नाशिक भागातील महाराष्ट्राचे प्रमुख भाजी/रोख पीक; पुरवठ्यानुसार किंमती झपाट्याने बदलतात.",
    "commonDiseases": "Purple Blotch, Thrips, Basal Rot",
    "recommendedFertilizer": "NPK 100:50:50 kg/ha, nitrogen in 2 splits",
    "imageUrl": "/crops/onion.jpg"
  },
  {
    "nameEn": "Tomato",
    "nameHi": "टमाटर",
    "nameMr": "टोमॅटो",
    "scientificName": "Solanum lycopersicum",
    "soilType": "loamy, sandy",
    "season": "Rabi, Kharif",
    "sowingMonth": "June or October",
    "harvestMonth": "September or January",
    "waterRequirement": "Medium",
    "avgYield": "150–200 quintal/acre",
    "avgYieldHi": "150–200 क्विंटल/एकर",
    "avgYieldMr": "150–200 क्विंटल/एकर",
    "priceRange": "₹800–2000/quintal (highly variable)",
    "priceRangeHi": "₹800–2000/क्विंटल (अत्यंत परिवर्तनशील)",
    "priceRangeMr": "₹800–2000/क्विंटल (अत्यंत परिवर्तनशील)",
    "description": "High-value vegetable best grown on raised beds with drip irrigation to avoid fruit cracking.",
    "descriptionHi": "फल के टूटने से बचने के लिए ड्रिप सिंचाई के साथ उठी हुई क्यारियों पर सबसे अच्छी उगने वाली उच्च-मूल्य वाली सब्जी।",
    "descriptionMr": "फळ तडकणे टाळण्यासाठी ठिबक सिंचनासह उंच वरंब्यांवर चांगले येणारे उच्च-मूल्याचे भाजीपाला पीक.",
    "commonDiseases": "Early Blight, Blossom-End Rot, Fruit Borer",
    "recommendedFertilizer": "NPK 100:50:50 kg/ha; calcium helps reduce blossom-end rot",
    "imageUrl": "/crops/tomato.jpg"
  },
  {
    "nameEn": "Potato",
    "nameHi": "आलू",
    "nameMr": "बटाटा",
    "scientificName": "Solanum tuberosum",
    "soilType": "loamy, sandy",
    "season": "Rabi",
    "sowingMonth": "October–November",
    "harvestMonth": "January–February",
    "waterRequirement": "Medium",
    "avgYield": "80–100 quintal/acre",
    "avgYieldHi": "80–100 क्विंटल/एकर",
    "avgYieldMr": "80–100 क्विंटल/एकर",
    "priceRange": "₹800–1400/quintal",
    "priceRangeHi": "₹800–1400/क्विंटल",
    "priceRangeMr": "₹800–1400/क्विंटल",
    "description": "Cool-season tuber crop needing loose, well-drained soil for good tuber development.",
    "descriptionHi": "अच्छे कंद विकास के लिए ढीली, अच्छी जल-निकासी वाली मिट्टी की आवश्यकता वाली ठंडे मौसम की कंद फसल।",
    "descriptionMr": "चांगल्या कंद विकासासाठी मोकळी, निचरा असलेली जमीन लागणारे थंड हंगामी कंद पीक.",
    "commonDiseases": "Late Blight, Early Blight, Common Scab",
    "recommendedFertilizer": "NPK 120:60:60 kg/ha",
    "imageUrl": "/crops/potato.jpg"
  },
  {
    "nameEn": "Brinjal (Eggplant)",
    "nameHi": "बैंगन",
    "nameMr": "वांगे",
    "scientificName": "Solanum melongena",
    "soilType": "loamy, sandy",
    "season": "Kharif, Rabi",
    "sowingMonth": "June or October",
    "harvestMonth": "September onward (long picking window)",
    "waterRequirement": "Medium",
    "avgYield": "120–160 quintal/acre",
    "avgYieldHi": "120–160 क्विंटल/एकर",
    "avgYieldMr": "120–160 क्विंटल/एकर",
    "priceRange": "₹1000–1800/quintal",
    "priceRangeHi": "₹1000–1800/क्विंटल",
    "priceRangeMr": "₹1000–1800/क्विंटल",
    "description": "Widely grown vegetable with a long harvest window of repeated pickings.",
    "descriptionHi": "बार-बार तुड़ाई के लंबे समय के साथ व्यापक रूप से उगाई जाने वाली सब्जी।",
    "descriptionMr": "वारंवार तोडणीच्या दीर्घ कालावधीसह मोठ्या प्रमाणात घेतली जाणारी भाजी.",
    "commonDiseases": "Fruit & Shoot Borer, Bacterial Wilt, Little Leaf",
    "recommendedFertilizer": "NPK 100:50:50 kg/ha",
    "imageUrl": "/crops/brinjal.jpg"
  },
  {
    "nameEn": "Cabbage",
    "nameHi": "पत्तागोभी",
    "nameMr": "कोबी",
    "scientificName": "Brassica oleracea var. capitata",
    "soilType": "loamy",
    "season": "Rabi",
    "sowingMonth": "September–October",
    "harvestMonth": "December–January",
    "waterRequirement": "Medium",
    "avgYield": "150–200 quintal/acre",
    "avgYieldHi": "150–200 क्विंटल/एकर",
    "avgYieldMr": "150–200 क्विंटल/एकर",
    "priceRange": "₹600–1200/quintal",
    "priceRangeHi": "₹600–1200/क्विंटल",
    "priceRangeMr": "₹600–1200/क्विंटल",
    "description": "Cool-season leafy vegetable that heads best in mild winter temperatures.",
    "descriptionHi": "हल्की सर्दियों में अच्छी तरह से सिर बनाने वाली ठंडे मौसम की पत्तेदार सब्जी।",
    "descriptionMr": "सौम्य हिवाळ्यात उत्तम कोबी धरून येणारी थंड हंगामी पानदार भाजी.",
    "commonDiseases": "Black Rot, Diamondback Moth, Clubroot",
    "recommendedFertilizer": "NPK 100:50:50 kg/ha",
    "imageUrl": "/crops/cabbage.jpg"
  },
  {
    "nameEn": "Cauliflower",
    "nameHi": "फूलगोभी",
    "nameMr": "फ्लॉवर",
    "scientificName": "Brassica oleracea var. botrytis",
    "soilType": "loamy",
    "season": "Rabi",
    "sowingMonth": "September–October",
    "harvestMonth": "December–January",
    "waterRequirement": "Medium",
    "avgYield": "100–140 quintal/acre",
    "avgYieldHi": "100–140 क्विंटल/एकर",
    "avgYieldMr": "100–140 क्विंटल/एकर",
    "priceRange": "₹800–1500/quintal",
    "priceRangeHi": "₹800–1500/क्विंटल",
    "priceRangeMr": "₹800–1500/क्विंटल",
    "description": "Related to cabbage; needs consistent moisture for compact, well-formed curds.",
    "descriptionHi": "गोभी से संबंधित; सघन, अच्छी बनावट वाली गांठों के लिए लगातार नमी की आवश्यकता होती है।",
    "descriptionMr": "कोबीशी संबंधित; घट्ट, चांगल्या आकाराच्या फुलांसाठी सातत्यपूर्ण ओलावा आवश्यक.",
    "commonDiseases": "Black Rot, Curd Blackening, Aphids",
    "recommendedFertilizer": "NPK 100:60:60 kg/ha",
    "imageUrl": "/crops/cauliflower.jpg"
  },
  {
    "nameEn": "Okra (Bhendi)",
    "nameHi": "भिंडी",
    "nameMr": "भेंडी",
    "scientificName": "Abelmoschus esculentus",
    "soilType": "loamy, sandy",
    "season": "Kharif, Zaid",
    "sowingMonth": "June or February",
    "harvestMonth": "August onward (long picking window)",
    "waterRequirement": "Medium",
    "avgYield": "60–90 quintal/acre",
    "avgYieldHi": "60–90 क्विंटल/एकर",
    "avgYieldMr": "60–90 क्विंटल/एकर",
    "priceRange": "₹1200–2000/quintal",
    "priceRangeHi": "₹1200–2000/क्विंटल",
    "priceRangeMr": "₹1200–2000/क्विंटल",
    "description": "Fast-growing summer/monsoon vegetable with frequent picking over an extended season.",
    "descriptionHi": "लंबे मौसम में बार-बार तुड़ाई वाली तेजी से बढ़ने वाली ग्रीष्म/मानसून सब्जी।",
    "descriptionMr": "दीर्घ हंगामात वारंवार तोडणी असलेली लवकर वाढणारी उन्हाळी/पावसाळी भाजी.",
    "commonDiseases": "Yellow Vein Mosaic Virus, Fruit Borer, Powdery Mildew",
    "recommendedFertilizer": "NPK 80:40:40 kg/ha",
    "imageUrl": "/crops/okra.jpg"
  },
  {
    "nameEn": "Chilli",
    "nameHi": "मिर्च",
    "nameMr": "मिरची",
    "scientificName": "Capsicum annuum",
    "soilType": "loamy, black",
    "season": "Kharif, Rabi",
    "sowingMonth": "June or November",
    "harvestMonth": "October onward (multiple pickings)",
    "waterRequirement": "Medium",
    "avgYield": "25–35 quintal/acre (dry)",
    "avgYieldHi": "25–35 क्विंटल/एकर (सूखा)",
    "avgYieldMr": "25–35 क्विंटल/एकर (सुका)",
    "priceRange": "₹8000–14000/quintal (dry, variable)",
    "priceRangeHi": "₹8000–14000/क्विंटल (सूखी, परिवर्तनशील)",
    "priceRangeMr": "₹8000–14000/क्विंटल (सुकी, परिवर्तनशील)",
    "description": "High-value spice crop grown for both fresh green and dried red chilli markets.",
    "descriptionHi": "ताजी हरी और सूखी लाल मिर्च दोनों बाजारों के लिए उगाई जाने वाली उच्च-मूल्य वाली मसाला फसल।",
    "descriptionMr": "ताजी हिरवी व सुकी लाल मिरची अशा दोन्ही बाजारांसाठी घेतले जाणारे उच्च-मूल्याचे मसाला पीक.",
    "commonDiseases": "Thrips/Leaf Curl Complex, Anthracnose, Wilt",
    "recommendedFertilizer": "NPK 100:50:50 kg/ha",
    "imageUrl": "/crops/chilli.jpg"
  },
  {
    "nameEn": "Turmeric",
    "nameHi": "हल्दी",
    "nameMr": "हळद",
    "scientificName": "Curcuma longa",
    "soilType": "loamy, clay",
    "season": "Kharif",
    "sowingMonth": "May–June",
    "harvestMonth": "January–March (8–9 month duration)",
    "waterRequirement": "High",
    "avgYield": "80–100 quintal/acre (fresh rhizome)",
    "avgYieldHi": "80–100 क्विंटल/एकर (ताजा प्रकंद)",
    "avgYieldMr": "80–100 क्विंटल/एकर (ताजा कंद)",
    "priceRange": "₹6000–8000/quintal",
    "priceRangeHi": "₹6000–8000/क्विंटल",
    "priceRangeMr": "₹6000–8000/क्विंटल",
    "description": "Long-duration rhizome spice crop; Sangli/Hingoli belts are known turmeric markets.",
    "descriptionHi": "लंबी अवधि की जड़-प्रकंद मसाला फसल; सांगली/हिंगोली क्षेत्र प्रसिद्ध हल्दी बाजार हैं।",
    "descriptionMr": "दीर्घ कालावधीचे कंद-मसाला पीक; सांगली/हिंगोली भाग प्रसिद्ध हळद बाजार आहेत.",
    "commonDiseases": "Rhizome Rot, Leaf Blotch, Leaf Spot",
    "recommendedFertilizer": "NPK 60:50:50 kg/ha",
    "imageUrl": "/crops/turmeric.jpg"
  },
  {
    "nameEn": "Ginger",
    "nameHi": "अदरक",
    "nameMr": "आले",
    "scientificName": "Zingiber officinale",
    "soilType": "loamy",
    "season": "Kharif",
    "sowingMonth": "May–June",
    "harvestMonth": "December–January",
    "waterRequirement": "High",
    "avgYield": "70–90 quintal/acre",
    "avgYieldHi": "70–90 क्विंटल/एकर",
    "avgYieldMr": "70–90 क्विंटल/एकर",
    "priceRange": "₹5000–9000/quintal (variable)",
    "priceRangeHi": "₹5000–9000/क्विंटल (परिवर्तनशील)",
    "priceRangeMr": "₹5000–9000/क्विंटल (परिवर्तनशील)",
    "description": "Rhizome spice crop needing well-drained, humus-rich soil and partial shade.",
    "descriptionHi": "अच्छी जल-निकासी, ह्यूमस-समृद्ध मिट्टी और आंशिक छाया की आवश्यकता वाली प्रकंद मसाला फसल।",
    "descriptionMr": "चांगला निचरा, कुजबुज-समृद्ध जमीन व आंशिक सावलीची गरज असणारे कंद मसाला पीक.",
    "commonDiseases": "Rhizome Rot, Bacterial Wilt, Leaf Spot",
    "recommendedFertilizer": "NPK 75:50:50 kg/ha",
    "imageUrl": "/crops/ginger.jpg"
  },
  {
    "nameEn": "Garlic",
    "nameHi": "लहसुन",
    "nameMr": "लसूण",
    "scientificName": "Allium sativum",
    "soilType": "loamy, sandy",
    "season": "Rabi",
    "sowingMonth": "October–November",
    "harvestMonth": "February–March",
    "waterRequirement": "Low",
    "avgYield": "40–60 quintal/acre",
    "avgYieldHi": "40–60 क्विंटल/एकर",
    "avgYieldMr": "40–60 क्विंटल/एकर",
    "priceRange": "₹4000–10000/quintal (highly variable)",
    "priceRangeHi": "₹4000–10000/क्विंटल (अत्यंत परिवर्तनशील)",
    "priceRangeMr": "₹4000–10000/क्विंटल (अत्यंत परिवर्तनशील)",
    "description": "Bulb crop that prefers cool weather during vegetative growth and dry weather at maturity.",
    "descriptionHi": "वानस्पतिक विकास के दौरान ठंडे मौसम और परिपक्वता पर शुष्क मौसम पसंद करने वाली बल्ब फसल।",
    "descriptionMr": "वाढीच्या काळात थंड हवामान आणि परिपक्वतेवेळी कोरडे हवामान आवडणारे कांदा (बल्ब) पीक.",
    "commonDiseases": "Purple Blotch, Thrips, White Rot",
    "recommendedFertilizer": "NPK 60:40:40 kg/ha",
    "imageUrl": "/crops/garlic.jpg"
  },
  {
    "nameEn": "Grapes",
    "nameHi": "अंगूर",
    "nameMr": "द्राक्ष",
    "scientificName": "Vitis vinifera",
    "soilType": "loamy, sandy",
    "season": "Perennial (pruned twice yearly)",
    "sowingMonth": "Planted June–July; pruned Oct and April",
    "harvestMonth": "January–March (main season)",
    "waterRequirement": "Medium",
    "avgYield": "80–120 quintal/acre",
    "avgYieldHi": "80–120 क्विंटल/एकर",
    "avgYieldMr": "80–120 क्विंटल/एकर",
    "priceRange": "₹3000–6000/quintal (table grapes)",
    "priceRangeHi": "₹3000–6000/क्विंटल (टेबल अंगूर)",
    "priceRangeMr": "₹3000–6000/क्विंटल (टेबल द्राक्ष)",
    "description": "Nashik region's signature export crop; trellised vines need precise double-pruning cycles.",
    "descriptionHi": "नाशिक क्षेत्र की प्रमुख निर्यात फसल; ट्रेलिस वाली बेलों को सटीक दोहरे छंटाई चक्रों की आवश्यकता होती है।",
    "descriptionMr": "नाशिक भागातील प्रमुख निर्यात पीक; जाळीवरील वेलींना अचूक दुहेरी छाटणी चक्रांची गरज असते.",
    "commonDiseases": "Downy Mildew, Powdery Mildew, Anthracnose",
    "recommendedFertilizer": "NPK 400:200:200 g/vine/year staged across phenophases",
    "imageUrl": "/crops/grapes.jpg"
  },
  {
    "nameEn": "Banana",
    "nameHi": "केला",
    "nameMr": "केळी",
    "scientificName": "Musa spp.",
    "soilType": "loamy, clay",
    "season": "Perennial",
    "sowingMonth": "June or February (tissue-culture plantlets)",
    "harvestMonth": "11–13 months after planting",
    "waterRequirement": "High",
    "avgYield": "250–350 quintal/acre",
    "avgYieldHi": "250–350 क्विंटल/एकर",
    "avgYieldMr": "250–350 क्विंटल/एकर",
    "priceRange": "₹800–1500/quintal",
    "priceRangeHi": "₹800–1500/क्विंटल",
    "priceRangeMr": "₹800–1500/क्विंटल",
    "description": "Jalgaon is a major banana belt; the crop needs consistent irrigation and wind protection.",
    "descriptionHi": "जलगाँव प्रमुख केला क्षेत्र है; फसल को लगातार सिंचाई और हवा से सुरक्षा की आवश्यकता होती है।",
    "descriptionMr": "जळगाव हे केळीचे प्रमुख क्षेत्र आहे; पिकास सातत्यपूर्ण सिंचन व वाऱ्यापासून संरक्षण लागते.",
    "commonDiseases": "Panama Wilt, Sigatoka Leaf Spot, Bunchy Top Virus",
    "recommendedFertilizer": "NPK 200:60:300 g/plant/year in split doses",
    "imageUrl": "/crops/banana.jpg"
  },
  {
    "nameEn": "Mango",
    "nameHi": "आम",
    "nameMr": "आंबा",
    "scientificName": "Mangifera indica",
    "soilType": "loamy, red",
    "season": "Perennial",
    "sowingMonth": "June–July (grafted saplings)",
    "harvestMonth": "March–June",
    "waterRequirement": "Medium",
    "avgYield": "40–60 quintal/acre (mature orchard)",
    "avgYieldHi": "40–60 क्विंटल/एकर (परिपक्व बाग)",
    "avgYieldMr": "40–60 क्विंटल/एकर (परिपक्व बाग)",
    "priceRange": "₹3000–8000/quintal (variety-dependent, e.g. Alphonso)",
    "priceRangeHi": "₹3000–8000/क्विंटल (किस्म-निर्भर, जैसे अल्फांसो)",
    "priceRangeMr": "₹3000–8000/क्विंटल (जात-आधारित, जसे आल्फान्सो)",
    "description": "Konkan's Alphonso (Hapus) is Maharashtra's most iconic fruit crop, grown on lateritic hill soils.",
    "descriptionHi": "कोंकण का अल्फांसो (हापुस) महाराष्ट्र की सबसे प्रतिष्ठित फल फसल है, जो लैटेराइट पहाड़ी मिट्टी पर उगाई जाती है।",
    "descriptionMr": "कोकणातील आल्फान्सो (हापूस) हे महाराष्ट्राचे सर्वात प्रतिष्ठित फळ पीक असून ते लॅटेराइट डोंगराळ जमिनीवर घेतले जाते.",
    "commonDiseases": "Powdery Mildew, Anthracnose, Fruit Fly",
    "recommendedFertilizer": "NPK 500:250:500 g/tree/year for a mature tree",
    "imageUrl": "/crops/mango.jpg"
  },
  {
    "nameEn": "Pomegranate",
    "nameHi": "अनार",
    "nameMr": "डाळिंब",
    "scientificName": "Punica granatum",
    "soilType": "loamy, black",
    "season": "Perennial (bahar-based flowering)",
    "sowingMonth": "June–July",
    "harvestMonth": "5–6 months after flowering (bahar)",
    "waterRequirement": "Low",
    "avgYield": "80–100 quintal/acre",
    "avgYieldHi": "80–100 क्विंटल/एकर",
    "avgYieldMr": "80–100 क्विंटल/एकर",
    "priceRange": "₹4000–9000/quintal",
    "priceRangeHi": "₹4000–9000/क्विंटल",
    "priceRangeMr": "₹4000–9000/क्विंटल",
    "description": "Drought-tolerant fruit crop centered in Solapur/Ahmednagar, managed through timed 'bahar' flowering cycles.",
    "descriptionHi": "सोलापुर/अहमदनगर में केंद्रित सूखा-सहनशील फल फसल, समयबद्ध 'बहार' फूल चक्रों के माध्यम से प्रबंधित।",
    "descriptionMr": "सोलापूर/अहमदनगरवर केंद्रित दुष्काळ-सहनशील फळ पीक, वेळेवर 'बहार' फुलोरा चक्रांद्वारे व्यवस्थापित.",
    "commonDiseases": "Bacterial Blight, Wilt, Fruit Borer",
    "recommendedFertilizer": "NPK 625:250:250 g/plant/year",
    "imageUrl": "/crops/pomegranate.jpg"
  },
  {
    "nameEn": "Orange (Nagpur Mandarin)",
    "nameHi": "संतरा (नागपुरी)",
    "nameMr": "संत्रा",
    "scientificName": "Citrus reticulata",
    "soilType": "loamy, black",
    "season": "Perennial (two flowering flushes)",
    "sowingMonth": "June–July or February",
    "harvestMonth": "November–January (Ambia) or June–July (Mrig)",
    "waterRequirement": "Medium",
    "avgYield": "60–90 quintal/acre",
    "avgYieldHi": "60–90 क्विंटल/एकर",
    "avgYieldMr": "60–90 क्विंटल/एकर",
    "priceRange": "₹1500–3500/quintal",
    "priceRangeHi": "₹1500–3500/क्विंटल",
    "priceRangeMr": "₹1500–3500/क्विंटल",
    "description": "Vidarbha's Nagpur mandarin is one of India's best-known citrus varieties.",
    "descriptionHi": "विदर्भ का नागपुरी संतरा भारत की सबसे प्रसिद्ध साइट्रस किस्मों में से एक है।",
    "descriptionMr": "विदर्भातील नागपूर संत्रा ही भारतातील सर्वात प्रसिद्ध लिंबूवर्गीय जातींपैकी एक आहे.",
    "commonDiseases": "Citrus Canker, Gummosis, Leaf Miner",
    "recommendedFertilizer": "NPK 600:200:200 g/tree/year for bearing trees",
    "imageUrl": "/crops/orange.jpg"
  },
  {
    "nameEn": "Sapota (Chikoo)",
    "nameHi": "चीकू",
    "nameMr": "चिकू",
    "scientificName": "Manilkara zapota",
    "soilType": "loamy, sandy",
    "season": "Perennial",
    "sowingMonth": "June–July (grafted saplings)",
    "harvestMonth": "Year-round with peak in Nov–Feb",
    "waterRequirement": "Medium",
    "avgYield": "100–150 quintal/acre (mature orchard)",
    "avgYieldHi": "100–150 क्विंटल/एकर (परिपक्व बाग)",
    "avgYieldMr": "100–150 क्विंटल/एकर (परिपक्व बाग)",
    "priceRange": "₹1500–2500/quintal",
    "priceRangeHi": "₹1500–2500/क्विंटल",
    "priceRangeMr": "₹1500–2500/क्विंटल",
    "description": "Hardy evergreen fruit tree well suited to coastal Konkan; bears almost continuously once mature.",
    "descriptionHi": "तटीय कोंकण के लिए उपयुक्त कठोर सदाबहार फल वृक्ष; परिपक्व होने पर लगभग लगातार फल देता है।",
    "descriptionMr": "किनारपट्टीच्या कोकणासाठी योग्य कठोर सदाहरित फळझाड; परिपक्व झाल्यावर जवळपास सतत फळ देते.",
    "commonDiseases": "Leaf Spot, Bark Borer, Fruit Fly",
    "recommendedFertilizer": "NPK 500:250:250 g/tree/year",
    "imageUrl": "/crops/sapota.jpg"
  },
  {
    "nameEn": "Guava",
    "nameHi": "अमरूद",
    "nameMr": "पेरू",
    "scientificName": "Psidium guajava",
    "soilType": "loamy, sandy",
    "season": "Perennial (two crops: Ambe & Mrig bahar)",
    "sowingMonth": "June–July or February",
    "harvestMonth": "October–December or June–July",
    "waterRequirement": "Low",
    "avgYield": "100–150 quintal/acre",
    "avgYieldHi": "100–150 क्विंटल/एकर",
    "avgYieldMr": "100–150 क्विंटल/एकर",
    "priceRange": "₹1000–2000/quintal",
    "priceRangeHi": "₹1000–2000/क्विंटल",
    "priceRangeMr": "₹1000–2000/क्विंटल",
    "description": "Resilient fruit tree that tolerates poor soils better than most orchard crops.",
    "descriptionHi": "अधिकांश बाग फसलों की तुलना में खराब मिट्टी को बेहतर सहन करने वाला लचीला फल वृक्ष।",
    "descriptionMr": "बहुतेक बागायती पिकांपेक्षा खराब जमीन चांगली सहन करणारे लवचिक फळझाड.",
    "commonDiseases": "Wilt, Anthracnose, Fruit Fly",
    "recommendedFertilizer": "NPK 300:150:300 g/tree/year",
    "imageUrl": "/crops/guava.jpg"
  },
  {
    "nameEn": "Papaya",
    "nameHi": "पपीता",
    "nameMr": "पपई",
    "scientificName": "Carica papaya",
    "soilType": "loamy, sandy",
    "season": "Perennial (planted year-round in irrigated areas)",
    "sowingMonth": "June–July or February–March",
    "harvestMonth": "9–11 months after planting",
    "waterRequirement": "Medium",
    "avgYield": "400–600 quintal/acre",
    "avgYieldHi": "400–600 क्विंटल/एकर",
    "avgYieldMr": "400–600 क्विंटल/एकर",
    "priceRange": "₹500–1200/quintal",
    "priceRangeHi": "₹500–1200/क्विंटल",
    "priceRangeMr": "₹500–1200/क्विंटल",
    "description": "Fast-yielding fruit crop that bears within a year; sensitive to waterlogging.",
    "descriptionHi": "एक वर्ष के भीतर फल देने वाली तेजी से उपज देने वाली फल फसल; जलभराव के प्रति संवेदनशील।",
    "descriptionMr": "एका वर्षात फळ देणारे लवकर उत्पादन देणारे फळ पीक; पाणी साचण्यास संवेदनशील.",
    "commonDiseases": "Papaya Ring Spot Virus, Root Rot, Powdery Mildew",
    "recommendedFertilizer": "NPK 250:250:500 g/plant/year",
    "imageUrl": "/crops/papaya.jpg"
  },
  {
    "nameEn": "Watermelon",
    "nameHi": "तरबूज",
    "nameMr": "कलिंगड",
    "scientificName": "Citrullus lanatus",
    "soilType": "sandy, loamy",
    "season": "Zaid",
    "sowingMonth": "January–February",
    "harvestMonth": "April–May",
    "waterRequirement": "Medium",
    "avgYield": "150–200 quintal/acre",
    "avgYieldHi": "150–200 क्विंटल/एकर",
    "avgYieldMr": "150–200 क्विंटल/एकर",
    "priceRange": "₹600–1200/quintal",
    "priceRangeHi": "₹600–1200/क्विंटल",
    "priceRangeMr": "₹600–1200/क्विंटल",
    "description": "Summer melon grown on riverbed sandy tracts, timed to ripen before peak summer heat.",
    "descriptionHi": "चरम ग्रीष्म ताप से पहले पकने के लिए समयबद्ध, नदी-किनारे रेतीली पट्टियों पर उगाया जाने वाला ग्रीष्म तरबूज।",
    "descriptionMr": "उष्णतेपूर्वी पिकण्यासाठी वेळेवर, नदीकाठच्या वाळूमिश्रित पट्ट्यांवर घेतले जाणारे उन्हाळी कलिंगड.",
    "commonDiseases": "Fusarium Wilt, Downy Mildew, Fruit Fly",
    "recommendedFertilizer": "NPK 60:40:40 kg/ha",
    "imageUrl": "/crops/watermelon.jpg"
  },
  {
    "nameEn": "Sesame (Til)",
    "nameHi": "तिल",
    "nameMr": "तीळ",
    "scientificName": "Sesamum indicum",
    "soilType": "sandy, loamy",
    "season": "Kharif, Zaid",
    "sowingMonth": "June–July or February",
    "harvestMonth": "September or May",
    "waterRequirement": "Low",
    "avgYield": "3–4 quintal/acre",
    "avgYieldHi": "3–4 क्विंटल/एकर",
    "avgYieldMr": "3–4 क्विंटल/एकर",
    "priceRange": "₹9000–12000/quintal",
    "priceRangeHi": "₹9000–12000/क्विंटल",
    "priceRangeMr": "₹9000–12000/क्विंटल",
    "description": "Short-duration, drought-hardy oilseed traditionally intercropped with pulses.",
    "descriptionHi": "छोटी अवधि की, सूखा-कठोर तिलहन, पारंपरिक रूप से दलहन के साथ अंतरफसल के रूप में उगाई जाती है।",
    "descriptionMr": "अल्प कालावधीचे, दुष्काळ-कठोर तेलबिया पीक, पारंपरिकपणे डाळीबरोबर आंतरपिक म्हणून घेतले जाते.",
    "commonDiseases": "Phyllody, Leaf Spot, Stem/Root Rot",
    "recommendedFertilizer": "NPK 25:25:0 kg/ha",
    "imageUrl": "/crops/sesame.jpg"
  },
  {
    "nameEn": "Castor",
    "nameHi": "अरंडी",
    "nameMr": "एरंड",
    "scientificName": "Ricinus communis",
    "soilType": "sandy, loamy, black",
    "season": "Kharif",
    "sowingMonth": "June–July",
    "harvestMonth": "December onward (multiple pickings)",
    "waterRequirement": "Low",
    "avgYield": "10–14 quintal/acre",
    "avgYieldHi": "10–14 क्विंटल/एकर",
    "avgYieldMr": "10–14 क्विंटल/एकर",
    "priceRange": "₹6000–7000/quintal",
    "priceRangeHi": "₹6000–7000/क्विंटल",
    "priceRangeMr": "₹6000–7000/क्विंटल",
    "description": "Hardy industrial oilseed tolerant of poor soils and moisture stress.",
    "descriptionHi": "खराब मिट्टी और नमी तनाव सहन करने वाला कठोर औद्योगिक तिलहन।",
    "descriptionMr": "खराब जमीन व पाण्याचा ताण सहन करणारे कठोर औद्योगिक तेलबिया पीक.",
    "commonDiseases": "Wilt, Grey Rot, Semi-looper",
    "recommendedFertilizer": "NPK 60:40:0 kg/ha",
    "imageUrl": "/crops/castor.jpg"
  },
  {
    "nameEn": "Mustard",
    "nameHi": "सरसों",
    "nameMr": "मोहरी / राई",
    "scientificName": "Brassica juncea",
    "soilType": "loamy, sandy",
    "season": "Rabi",
    "sowingMonth": "October",
    "harvestMonth": "February",
    "waterRequirement": "Low",
    "avgYield": "5–7 quintal/acre",
    "avgYieldHi": "5–7 क्विंटल/एकर",
    "avgYieldMr": "5–7 क्विंटल/एकर",
    "priceRange": "₹5000–5800/quintal",
    "priceRangeHi": "₹5000–5800/क्विंटल",
    "priceRangeMr": "₹5000–5800/क्विंटल",
    "description": "Cool-season oilseed often grown as a border/mixed crop alongside chickpea or wheat.",
    "descriptionHi": "ठंडे मौसम की तिलहन, अक्सर चना या गेहूँ के साथ सीमा/मिश्रित फसल के रूप में उगाई जाती है।",
    "descriptionMr": "थंड हंगामी तेलबिया पीक, सहसा हरभरा किंवा गहूसोबत सीमा/मिश्र पीक म्हणून घेतले जाते.",
    "commonDiseases": "Alternaria Blight, Aphids, White Rust",
    "recommendedFertilizer": "NPK 60:40:20 kg/ha",
    "imageUrl": "/crops/mustard.jpg"
  },
  {
    "nameEn": "Lentil (Masoor)",
    "nameHi": "मसूर",
    "nameMr": "मसूर",
    "scientificName": "Lens culinaris",
    "soilType": "loamy, clay",
    "season": "Rabi",
    "sowingMonth": "October–November",
    "harvestMonth": "February–March",
    "waterRequirement": "Low",
    "avgYield": "6–8 quintal/acre",
    "avgYieldHi": "6–8 क्विंटल/एकर",
    "avgYieldMr": "6–8 क्विंटल/एकर",
    "priceRange": "₹6000–6800/quintal",
    "priceRangeHi": "₹6000–6800/क्विंटल",
    "priceRangeMr": "₹6000–6800/क्विंटल",
    "description": "Cool-season pulse grown mainly on conserved soil moisture after the monsoon.",
    "descriptionHi": "मानसून के बाद संरक्षित मिट्टी की नमी पर मुख्य रूप से उगाई जाने वाली ठंडे मौसम की दलहन।",
    "descriptionMr": "पावसाळ्यानंतर संरक्षित जमिनीच्या ओलाव्यावर मुख्यतः घेतली जाणारी थंड हंगामी डाळ.",
    "commonDiseases": "Rust, Wilt, Aphids",
    "recommendedFertilizer": "NPK 20:40:0 kg/ha basal",
    "imageUrl": "/crops/lentil.jpg"
  }
];

module.exports = { CROP_CATALOG_SEED };
